# This is a basic workflow to help you get started with Actions

name: Build /e/OS ROM

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Get system info
      run: |
        whoami
        uname -a
        pwd
        ls -la ~/work
        df -h
        mount

    - name: Create directories
      run: | 
          mkdir -p ~/work/e/src ~/work/e/zips ~/work/e/logs ~/work/e/ccache
          ls -la ~/work/e

#    - name: Pull docker image for build process
#      run: docker pull registry.gitlab.e.foundation:5000/e/os/docker-lineage-cicd:community
    
#    - name: Build ROM
#      run: docker run -v ~/work/e/src:/srv/src -v ~/work/e/zips:/srv/zips -v ~/work/e/logs:/srv/logs -v ~/work/e/ccache:/srv/ccache -e BRANCH_NAME=v1-pie -e DEVICE_LIST=capricorn -e REPO=https://gitlab.e.foundation/e/os/android.git registry.gitlab.e.foundation:5000/e/os/docker-lineage-cicd:community
